version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vik&rajan1
      POSTGRES_DB: lib

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
